## This is Hexo-Theme-MDUI
## Author:186526(https://github.com/186526)
version: 0.2
favicon: https://drive.almondcloud.cn/f/q4R4U9/IMG_3314.ico
color:
  primary: "blue"
  accent: "white"
icon: https://drive.almondcloud.cn/f/q4R4U9/IMG_3314.ico
avatar: https://ooo.0x0.ooo/2024/10/07/O4wloF.jpg
fab:
  enable: true
  ## only mdui-icon material-icons
  icon: home
  url: /
drawer:
  personal: 
    enable: true
    des: "Hexo-Theme-MDUI"
  darkmode_btn: true
  archives: true
  social:
    enable: true
    links: 
      Github:  https://github.com/ghriver
      QQ: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=2025650064
  pages:
    enable: true
    links:
      'Guestbook': guestbook/
      'About': about/
  friends: 
    enable: true
    links: 
      186526: 
        url: https://186526.xyz
        icon: https://cdn.jsdelivr.net/gh/186526/hexo-theme-lx/source/images/avatar.jpg

pjax_enable: true

footer: 
  MoeICP:20240283
## Use Valine as comment system
comment:
  enable: false
  appid: ''
  appkey: ''
  notify: false
  verify: false
  placeholder: 'Say something.' 
  avatar: identicon
  guest_info: nick,mail,link
  pageSize: 10
  language: zh-cn

sources_cdn: 
  MDUI_js: "https://cdn.jsdelivr.net/npm/mdui/dist/js/mdui.min.js"
  MDUI_css: "https://cdn.jsdelivr.net/npm/mdui/dist/css/mdui.min.css"
  Valine: "https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/Valine.min.js"
  jquery: "https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"
  jquery_pjax: "https://cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js"
  main_js: "https://cdn.jsdelivr.net/gh/186526/hexo-theme-mduilw@master/source/js/main.min.js"
  main_css: "https://cdn.jsdelivr.net/gh/186526/hexo-theme-mduilw@master/source/css/main.min.css"
  ## ~~感谢菠萝大佬提供的国内cdn（使用阿里云cdn~~
  ## jsd yyds

twikoo:
  enable: true
  visitor: true
  envId: https://twikoo-mirror.ghriver.top
  # region: ap-guangzhou # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
